language: java
jdk:
- oraclejdk11
dist: trusty
addons:
  sonarcloud:
    organization: hycom
    token: "$SONAR_TOKEN"
before_install:
- cd src
script:
  - mvn clean verify sonar:sonar -Pcoverage
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: MaJF5yR7pD52tVI/BQJ7hohFBD56SY4k5oWtjF81Igr29OBAdy46hj7G5Fgltps/2ObivXdFCwHhxUtuvP0an3Seiom+VxJRy+IMk3vSjNiQCzKhGJzi8IRDxBUWM3Epb60HHfOpmQVe6lUF84wepVqStwq+VSdVa6G1DUWCDso/Qao2UHnPRketVsEII+nrqvZh3bwXbeZDlp81o5WCnj4tWAIy61mACmeSDYJKcgxwxYKNM0br9hPM3G280CjGgNEAmWhPOH6VG549Ox5hwZGch1KCiBPH0MtHdiSw8rnMOM72c8fFjZtCkyJiq4G8XQ6mOXJJ3GPrclGHr4NcDWMapFAn4G4P3CLL4XTxOFRYYZvmCuv3Iu8Dw5hU8lrn7aJ9NpY+67GlvCfoHRzW3va0Zico0fKExWOlb0vo8NuKdlwV4F2En5s2CTeO646Q7UaeJ9uOXx2zb3R6X9tjFyYzhT6KLhjgOqzjNLY+qniLCgdMD1YoVb7ARC2Y0sOem7TgANpebLk0Gd0x9BX8qCtykb7SAOOkLWEdhcXjTQWZOeoFTZOdBRQqmtBU2icISkUa17WRkAuD4Bx3i/7nu3WHok9v/pvCdbaOiIdyejbmSzpqG42S4KHc5OGnb78iyIh0/GEHPS6s6q5C8PElXmedpH7vCxcQmM8b0ecCUvM=
  skip_cleanup: true
  file: mokka/target/mokka-0.8.0-SNAPSHOT.jar

  on:
    tags: true
