@startuml

title Distribution package

package "mokka-<version>.jar" <<Node>> #LightYellow {

    package "mokka-api-<version>.jar" <<Node>> #Gold {
    }

    package "mokka-wiremock-<version>.jar" <<Node>> #Orange {
    }

    package "mokka-mockserver-<version>.jar" <<Node>> #Orange {
    }
}

@enduml