@startuml

title Maven artifacts

package "mokka" <<pom>> #LightYellow {

    package "mokka-api.jar" <<Node>> #Gold {
    }

    package adapter <<pom>> {
        package "mokka-wiremock.jar" <<Node>> #Orange {
        }

        package "mokka-mockserver.jar" <<Node>> #Orange {
        }
    }
}

@enduml