@startuml

title Directory structure in repository

package "repo" <<Folder>> #LightYellow {

    package "config" <<Folder>> #Gold {
    }

    package "doc" <<Folder>> #Gold {
    }

    package "src" <<Folder>> #Gold {
        package "mokka" <<Folder>> #Orange {

        }
        package "api" <<Folder>> #Orange {

        }
        package "adapter" <<Folder>> #Orange {
            package "wiremock" <<Folder>> #DarkOrange {

            }
            package "mockserver" <<Folder>> #DarkOrange {

            }
        }
    }
}

@enduml