@startuml

title Main interfaces

[mokka-wiremock]
[mokka-mockserver]

() REST as API
[mokka-mockserver] .up.> API : impl
[mokka-wiremock] .up.> API : impl
[mokka-api] -down-() API

() JSON_API as WM_API
[wiremock] -up-() WM_API
[mokka-wiremock]-down-(WM_API

() REST as MS_API
[mockserver] -up-() MS_API
[mokka-mockserver]-down-(MS_API

@enduml