@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml

title C1 Mokka context (draft)

Person(user, "User", "")
Person(adm, "Administrator", "")
System(mokka, "Mokka", "")
System_Ext(externalSystem, "External System", "")

Rel(user, mokka, "Uses", "HTTPS")
Rel(adm, mokka, "Uses", "HTTPS")
Rel(externalSystem, mokka, "Uses mocks", "SOAP/HTTPS, JMS, HTTP")

@enduml
